/*
 * Copyright 2019 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
 * Use of this source code is governed by an MIT-style license that can be found in the LICENSE file
 */

package gitprovider

import "errors"

const (
	// GitlabName ...
	GitlabName = "gitlab"
	// GitlabParamBaseURL ...
	GitlabParamBaseURL = "GITLAB_BASE_URL"
	// GitlabParamToken ...
	GitlabParamToken = "GITLAB_TOKEN"

	// GithubName ...
	GithubName = "github"
	// GithubParamBaseURL ...
	GithubParamBaseURL = "GITHUB_BASE_URL"
	// GithubParamToken ...
	GithubParamToken = "GITHUB_TOKEN"

	// BitbucketName ...
	BitbucketName = "bitbucket"
	// BitbucketParamBaseURL ...
	BitbucketParamBaseURL = "BITBUCKET_BASE_URL"
	// BitbucketParamClientID ...
	BitbucketParamClientID = "BITBUCKET_CLIENT_ID"
	// BitbucketParamClientSecret ...
	BitbucketParamClientSecret = "BITBUCKET_CLIENT_SECRET"
	// BitbucketParamUsername ...
	BitbucketParamUsername = "BITBUCKET_USERNAME"
	// BitbucketParamPassword ...
	BitbucketParamPassword = "BITBUCKET_PASSWORD"
)

var (
	// ErrInvalidAdditionalParams ...
	ErrInvalidAdditionalParams = errors.New("invalid additional params")
)
